
networks:
  my-network:
    driver: bridge

services:
  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_users:3306/users
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: adminpass
    depends_on:
      - db_users
    networks:
      - my-network

  devices:
    build:
      context: ./devices
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db_devices:3306/devices
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: adminpass
    depends_on:
      - db_devices
    networks:
      - my-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - users
      - devices
    networks:
      - my-network

  db_users:
    image: mysql:8.0.4
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: adminpass
    ports:
      - "3307:3306"
    networks:
        - my-network

  db_devices:
    image: mysql:8.0.4
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: devices
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: adminpass
    ports:
      - "3308:3306"
    networks:
      - my-network
